### ISSUE TITLE
Crash freeze + issues SW Clone Wars

### ISSUE THREAD

**Issue by Alktrottl** [danielkraak/GC-Loader#10]
Hello, I want to report several grave issues with the title: Star Wars Clone Wars Ger/EU [GSXD64/GSXP64]

The issues are sorted by their seriousness from low to high. 

Video jitter:
Startup at Clone Wars Logo video mode change and jitter distortion. This happens via CVBS, SCART RGB and GCplug digital out over hdmi. 
Fix via ingame reset, after reset game does not show jitter.

Audio distortion:
Audio distortion noticeable as soon as dolby surround logo shows up.
Audio distortion noticeable in menu (Campaign/Options/Multiplayer) regardless of mono/stereo/surround/dolby pro logic 2.
Audio distortion sporadic noticeable during any mission up to 3 minutes.

Crash/Freeze:
First hard freeze after successfull finishing mission "Evacuation of Rhen Var", upon hitting continue (replicable). If selecting continue console freezes and even pressing reset does not help, only power cycling console helps.

Second hard freeze after successfull finishing mission "Battle for Kashyyyk", upon hitting continue (replicable). If selecting continue console freezes and even pressing reset does not help, only power cycling console helps.

I have noticed that the freezes correspond with two cutscene videos which should play after mission success and continuing on with game. 
These cutscenes are:
Raxus Prime Intro
Return to Rhen Var

I was able to replicate all issues with German and Europe Version on 3 different PAL DOL 001 gamecubes with 3 different gcloader pnps, updated to current fw 1.1.0. The german iso used was of my own dump which checks out with the known md5 checksum on redump, the EU version is web loaded but also checks out with redump md5. 

The used micro sd card is a sandisk 64GB ultra class 1 UHS, formatted to fat 32. Setting in swiss to emulate read spead for this particular game did show no changes.

Thank you, if there is something I can test, pls let me know.

**Comment by Extrems** [comment]
Video jitter has been fixed in emukidid/swiss-gc@13c1c33.

**Comment by fille1976** [comment]
I also have problems with it,i just let it demo run,but game crashed.
I use a pal gamecube with gcloader with latest firmware and latest swiss.
Used ntsc redump version.

**Comment by tjanas** [comment]
> I also have problems with it,i just let it demo run,but game crashed.
> I use a pal gamecube with gcloader with latest firmware(1.1.0) and latest swiss(r963).
> Used ntsc redump version.

Latest firmware is [1.1.2](https://twitter.com/gcloader/status/1316439089185423360?s=21)

**Comment by fille1976** [comment]
seems to be down,can't reach the website here

**Comment by tjanas** [comment]
> seems to be down,can't reach the website here
> after update to 1.1.2,the problem is still there.

What if you set the game to be the boot.iso? Does the issue still occur?

**Comment by tjanas** [comment]
Confirmed. NTSC version of the game, on my NTSC GameCube DOL-001 IPL 1.1 with gcloader 1.1.2 and Swiss r963. Using s-video. Left the game at the title screen, and eventually the game crashed, dumping me back into Swiss.

**Comment by fille1976** [comment]
The bug is eplained by Extrems.
This game uses memory savestates to speed up loading, a feature they call fastload.
Swiss had to disable it to make the game behave better under it.
